### ISSUE TITLE
createTable command with name of existing *collection* returns HTTP 500

### ISSUE THREAD

**Issue by hemidactylus** [stargate/data-api#1561] opened 2024-10-17 15:49 UTC
If you create a table whose name is that of an existing collection, you get a HTTP 500 ==> which should be a 200.

_(Edit: I thought the response came back as a plain string, no json- I was mistaken. I have amended this issue accordingly)_

**Comment by amorton** [comment] 2024-11-19 22:14
should be fixed by the fix for #1562 but leaving open for testing

**Comment by amorton** [comment] 2024-11-26 00:34
when working on this make sure to cover the fault in #1562

**Comment by Hazel-Datastax** [comment] 2024-11-27 04:35
@hemidactylus I cannot reproduce the problem. Could you share your commands? Here are the commands I used:

**Creating a table with existing table name**
1. Create a table named `person`
```
{
    "createTable": {
        "name": "person",
        "definition": {
            "columns": {
                "id": "text",
                "age": "int",
                "name": "text",
                "city": "text"
            },
            "primaryKey": "id"
        },
        "options": {
            "ifNotExists": true
        }
    }
}
```
2. Create another table named `person` with fewer columns, different primaryKey and without `ifNotExists` flag
```
{
    "createTable": {
        "name": "person",
        "definition": {
            "columns": {
                "id": "text",
                "age": "int",
                "name": "text"
            },
            "primaryKey": "name"
        }
    }
}
```
3. I get 200 response with proper error message
```
{
    "status": {
        "ok": 0
    },
    "errors": [
        {
            "message": "The command attempted to add a table that already exists in the keyspace schema.\n\nThe command attempted to add the existing table: person.\n\nResend the command using a table name that does not exist in the keyspace.",
            "scope": "SCHEMA",
            "errorCode": "CANNOT_ADD_EXISTING_TABLE",
            "id": "95ae02b3-19c3-45da-b14c-1b5df09dc334",
            "family": "REQUEST",
            "title": "Table with the same name exists in the keyspace schema"
        }
    ]
}
```

**Creating a table with existing collection name**
1. Create a collection named `vector_collection`
```
{
    "createCollection": {
        "name": "vector_collection",
        "options": {
            "vector": {
                "size": 6,
                "function": "cosine"
            }
        }
    }
}
```
2. Create a table named `vector_collection` without `ifNotExists` flag
```
{
    "createTable": {
        "name": "vector_collection",
        "definition": {
            "columns": {
                "id": "text",
                "age": "int",
                "name": "text"
            },
            "primaryKey": "name"
        }
    }
}
```
3. I get 200 response with proper error message
```
{
    "status": {
        "ok": 0
    },
    "errors": [
        {
            "message": "The command attempted to add a table that already exists in the keyspace schema.\n\nThe command attempted to add the existing table: vector_collection.\n\nResend the command using a table name that does not exist in the keyspace.",
            "scope": "SCHEMA",
            "errorCode": "CANNOT_ADD_EXISTING_TABLE",
            "id": "12210f7b-1e06-4954-94d1-a5c340c9c920",
            "family": "REQUEST",
            "title": "Table with the same name exists in the keyspace schema"
        }
    ]
}
```

**Comment by Hazel-Datastax** [comment] 2024-11-27 18:01
Connected with Stefano and it seems not an issue anymore

**Closed by Hazel-Datastax** 2024-11-27 18:01 UTC
Labels: Bug, dec-hotfix, Feature - Tables
